# Zero-Clause BSD
# =============
#
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY
# DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
# AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
# OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

LOAD bar
LOAD MQ, bar
LOAD |bar|
LOAD -bar
LOAD MQ

.set VAL 0x20
.set SPAM VAL
.org VAL

STOR foo

JUMP label, 0:19
JUMP label, 20:39

JUMP+ label, 0:19
JUMP+ label, 20:39

STOR other_label, 8:19
STOR other_label, 28:39

other_label:
ADD foo
ADD |foo|

SUB foo
SUB |foo|

LSH
RSH

label:
    LOAD bar

HALT

foo:
    .word 0x32
bar:
    .word 0x21
vec:
    .wfill VAL, foo